"""
Django settings for WebsiteAPI project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't9djqjfbg90nh#)m^^g0ru7b)_(#%%1!(!j84_j5y!two&ow$8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'websockets_test',
    'chat',
    'channels',
    'django.contrib.contenttypes',
    'django.contrib.auth'
]

ROOT_URLCONF = 'websockets_test.urls'

WSGI_APPLICATION = 'websockets_test.wsgi.application'
ASGI_APPLICATION = 'websockets_test.routing.application'

# Environment settings
ENV_VARS = dict(os.environ)


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {

}

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join('chat/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
        },
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = ENV_VARS['STATIC_ROOT'] if 'STATIC_ROOT' in ENV_VARS else f"{ENV_VARS['CACHE_PATH']}/public"

# POST_MAX_SIZE - Ilimitado
DATA_UPLOAD_MAX_MEMORY_SIZE = None

# API Particular settings

CONFIG = {

    # Rotas sem autenticação
    "JWT_ROUTES_WHITE_LIST": [
        "GET_chat/",
        "GET_chat/{room_name}/"
    ],

    # Rotas que podem ser acessadas com token de app
    "JWT_ROUTES_USER_WHITE_LIST": [

    ],

    # Path do cache
    "CACHE_PATH": ENV_VARS['CACHE_PATH'],

    "URL_APP_API": "localhost",

    # MongoDB credentials
    "MONGODB": {
        "default": {
            'host': ENV_VARS['MONGO_DEFAULT_HOST'],
            'base': ENV_VARS['MONGO_DEFAULT_BASE'],
            'username': ENV_VARS['MONGO_DEFAULT_USER'],
            'password': ENV_VARS['MONGO_DEFAULT_PASS'],
            'port': int(ENV_VARS['MONGO_DEFAULT_PORT']),
        },
    },
}
